import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col items-center justify-center">
        <h1 className="neon bg-clip-text bg-repeat text-[10.5em] font-bold text-transparent font-disco-everyday">
          givensuman
        </h1>
      </main>
    </>
  );
}
